config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|vi/ do
    root 'home#index'

    get "/about", to: "home#about"
    get "/search", to: "courses#search"
    resources :courses
    resources :review_courses, except: [:new, :show]
    devise_for :users, skip: :omniauth_callbacks, controllers: { sessions: "sessions" }
    resources :users, except: [:new, :create]
    resources :lessons, only: :show
    resources :registers, only: [:edit, :update]
    resources :quiz_results, only: :create
    get "course/like/:course_id", to: "likes#save_like", as: :like_course
    resources :registers, only: :create

    namespace :admin do
      get "/", to: "base#index"
      get "/range", to: "base#range"
      resources :courses
      resources :users
      devise_scope :user do
        get "/login", to: "sessions#new"
        post "/login", to: "sessions#create"
        delete "/logout", to: "sessions#destroy"
      end
      namespace :charts do
        get "all_users_provider"
        get "users_registered_by"
        get "users_registered_course"
        get "users_registered_course_type"
      end
    end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauth_callbacks" }
end

app/views/layouts/admin/_admin_footer.html.slim
footer.main-footer
  strong
    | Copyright © 2014-2020
    a[href="http://adminlte.io"]
      | AdminLTE.io
    | .
  |  All rights reserved. 
  .float-right.d-none.d-sm-inline-block
    b
      | Version
    |  3.0.5

app/views/layouts/admin/_admin_navbar.html.slim
nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  ul.navbar-nav
    li.nav-item
      a.nav-link[data-widget="pushmenu" href="#" role="button"]
        i.fas.fa-bars
    li.nav-item.d-none.d-sm-inline-block
      = link_to "Athena", root_path, class: "nav-link"
  ul.navbar-nav.ml-auto
    li.nav-item.icon-lg
      = link_to image_tag('en.png'), locale:"en" if I18n.locale == :vi
    li.nav-item.icon-lg
      = link_to image_tag('vi.png'), locale:"vi" if I18n.locale == :en
    li.nav-item.d-none.d-sm-inline-block.dropdown
      a#navbarDropdownXL.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
        = image_tag(current_user.avatar.url(:thumb), class: "admin-avatar")
        = current_user.full_name.capitalize
      .dropdown-menu[aria-labelledby="navbarDropdownXL"]
        = link_to t("layouts.header.account_setting"), edit_admin_user_path(current_user), class: "dropdown-item" 
        = link_to t("layouts.header.log_out"), admin_logout_path, method: :delete, class: "dropdown-item"

app/views/layouts/admin/_admin_sidebar.html.slim
aside.main-sidebar.sidebar-dark-primary.elevation-4.position-fixed
  = link_to admin_path, class: "brand-link" do
    span.brand-text.font-weight-light
      | AdminLTE
  .slimScrollDiv style=("position: relative; overflow: hidden; width: auto; height: 652px;")
    .sidebar style=("min-height: 652px; overflow: hidden; width: auto; height: 652px;")
      .user-panel.mt-3.pb-3.mb-3.d-flex
        .image
          = image_tag(current_user.avatar.url(:thumb), class: "admin-avatar")
        .info
          a.d-block
            = link_to  current_user.full_name.capitalize, admin_user_path(current_user)
      nav.mt-2
        ul.nav.nav-pills.nav-sidebar.flex-column data-accordion="false" data-widget="treeview" role="menu"
          li.nav-item.has-treeview.menu-open
            a.nav-link.active href="/admin"
              i.nav-icon.fas.fa-tachometer-alt
              p
                span =t('admin.dash')
                i.right.fas.fa-angle-left
            ul.nav.nav-treeview
              li.nav-item.menu-item
                = link_to admin_users_path, class: "nav-link " do
                  i.far.fa-circle.nav-icon
                  p = t('admin.user')

              li.nav-item.menu-item
                = link_to admin_courses_path, class: "nav-link" do
                  i.far.fa-circle.nav-icon
                  p = t('admin.course')

script
  | $(document).ready(function(){
      const currentLocation = location.href;
      const menuItem = document.querySelectorAll('.menu-item > a')
      const pathBreadcrumb = document.querySelector('ol li:nth-child(2) > a')
      const menuLenght = menuItem.length
      for (let i = 0; i < menuLenght; i++) {
        if (menuItem[i].href == currentLocation)  {
          menuItem[i].className = "nav-link active"
        }
      }
      if (pathBreadcrumb != null) {
        for (let i = 0; i < menuLenght; i++) {
          if (menuItem[i].href ==  pathBreadcrumb.href){
            menuItem[i].className = "nav-link active"
          }
        }
      }
    });

app/views/layouts/admin/_breadcrumb.html.slim
.content-header
  .container-fluid
    .row.mb-2
      .col-12
        nav[aria-label="breadcrumb"]
          ol.breadcrumb.float-sm-right
            li.breadcrumb-item = link_to t("admin.dash"), admin_path
            - breadcrumbs = JSON.parse(sanitize yield(:breadcrumbs)) if content_for?(:breadcrumbs)
            - if breadcrumbs.present?
              - breadcrumbs.each do |breadcrumb|
                - case breadcrumb.class.to_s
                - when 'Array'
                  - string, link = breadcrumb
                  li.breadcrumb-item.active[aria-current="page"]
                    = link_to string, link
                - when 'String'
                  li.breadcrumb-item.active[aria-current="page"]
                    = content_tag :span, breadcrumb

app/views/layouts/admin/admin_index.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[http-equiv="x-ua-compatible" content="ie=edge"]
    title
      | AdminLTE 3 | Dashboard 3
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag Ckeditor.cdn_url
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.hold-transition.sidebar-mini
    .wrapper
      = render "layouts/admin/admin_navbar"
      = render "layouts/admin/admin_sidebar"
      = render "layouts/admin/breadcrumb"
      = yield
      = render "layouts/admin/admin_footer"
    #preloader

app/views/layouts/admin/admin_login.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    meta[http-equiv="x-ua-compatible" content="ie=edge"]
    title
      | Admin Athena
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag Ckeditor.cdn_url
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    script[src="https://kit.fontawesome.com/6d90f39943.js"]
  body
    header#header
      .container
        nav.navbar.navbar-expand-xl
          .navbar-brand.logo Admin
          button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContentXL" aria-controls="navbarSupportedContentXL" aria-expanded="false" aria-label="Toggle navigation"]
            span.navbar-toggler-icon
          #navbarSupportedContentXL.collapse.navbar-collapse
            ul.navbar-nav.ml-auto
              li.nav-item
                = link_to t('layouts.header.home'), root_path, class: "nav-link"
              li.flag
                = link_to image_tag('en.png'), locale:"en" if I18n.locale == :vi
              li.flag
                = link_to image_tag('vi.png'), locale:"vi" if I18n.locale == :en
              li.nav-item.get-login-btn
                = link_to t("admin.login_app"), new_user_session_path
    main.mt-5
      = yield