config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|vi/ do
    root 'home#index'

    get "/about", to: "home#about"
    get "/search", to: "courses#search"
    resources :courses
    resources :review_courses, except: [:new, :show]
    devise_for :users, skip: :omniauth_callbacks, controllers: { sessions: "sessions" }
    resources :users, except: [:new, :create]
    resources :lessons, only: :show
    resources :registers, only: [:edit, :update]
    resources :quiz_results, only: :create
    get "course/like/:course_id", to: "likes#save_like", as: :like_course
    resources :registers, only: :create

    namespace :admin do
      get "/", to: "base#index"
      get "/range", to: "base#range"
      resources :courses
      resources :users
      devise_scope :user do
        get "/login", to: "sessions#new"
        post "/login", to: "sessions#create"
        delete "/logout", to: "sessions#destroy"
      end
      namespace :charts do
        get "all_users_provider"
        get "users_registered_by"
        get "users_registered_course"
        get "users_registered_course_type"
      end
    end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauth_callbacks" }
end

app/views/shared/_banner.html.slim
section#hero.d-flex.justify-content-center.align-items-center
  .container.position-relative[data-aos="zoom-in" data-aos-delay="100"]
    h1
      | Learning Today,
      br
      | Leading Tomorrow
    = link_to t('banner.view_course'), courses_path, class: "btn-get-started"
div.notify.container
  =render("layouts/messages")

app/views/shared/_error_messages.html.erb
<% if @course.errors.any? %>
  <div id="error_explanation col-md-12">
    <ul class="row">
      <% @course.errors.full_messages.each do |message| %>
        <li class="col-md-6"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Site footer -->
<footer class="site-footer">
  <div class="container">

    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <h6><%= t('layouts.footer.about') %></h6>
        <p class="text-justify">
          <%= t('layouts.footer.vision') %>
        </p>
      </div>

      <div class="col-md-6 col-sm-6 col-xs-6">
        <div class="link-footer">
          <h6><%= t('layouts.footer.contact') %></h6>
          <div>
            <i class="fas fa-phone"></i>
            <span> <%= t('layouts.footer.phone') %> <%= link_to "(+84) 0123456789", "tel:0123456789" %></span>
          </div>
          <div>
            <i class="fas fa-envelope"></i>
            <span> Email: <%= link_to "jobup@gmail.com", "mailto:jobup@gmail.com", target: '_blank'  %></span>
          </div>
          <div>
            <i class="fas fa-map-marker-alt"></i>
            <span> <%= t('layouts.footer.location') %></span>
          </div>
        </div>
      </div>
    </div>

    <hr>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-6 col-xs-12">
        <p class="copyright-text"> 
          <%= t('layouts.footer.copyright') %> <span> &copy; </span>
          <%= link_to 'JobUp', root_path %>
        </p>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="social-icons">
          <li><%= link_to '', 'https://www.facebook.com/sun.awesome.academy/', target: '_blank', class: "facebook fab fa-facebook" %></li>
          <li><%= link_to '', 'https://github.com/awesome-academy', target: '_blank', class: "github fab fa-github" %></li>
          <li><%= link_to '', 'https://www.instagram.com/awesomeacademyhn', target: '_blank', class: "instagram fab fa-instagram" %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_footer.html.slim
footer#footer
  .footer-top
    .container
      .row
        .col-lg-3.col-md-6.footer-contact
          h3
            | Athena
          p
            = t('layouts.footer.addr')
            br
            strong
              = t('layouts.footer.phone')
            |  +84 123456789
            br
            strong
              = t('layouts.footer.email')
            |  athena@gmail.com
            br
        .col-lg-2.col-md-6.footer-links
          h4
            = t('layouts.footer.link')
          ul
            li
              i.fas.fa-angle-right
              = link_to t('layouts.header.home'), root_path
            li
              i.fas.fa-angle-right
              = link_to t('layouts.footer.about'), about_path
        .col-lg-3.col-md-6.footer-links
          h4
            = t('layouts.footer.our_course')
          ul
            li
              i.fas.fa-angle-right
              = link_to "Web Design"
            li
              i.fas.fa-angle-right
              = link_to "Web Development"
            li
              i.fas.fa-angle-right
              = link_to "Product Management"
            li
              i.fas.fa-angle-right
              = link_to "Marketing"
        .col-lg-4.col-md-6.footer-newsletter
          h4
            = t('layouts.footer.about')
          p
            = t('layouts.footer.about_cont')
  .container.d-md-flex.py-4
    .mr-md-auto.text-center.text-md-left
      .copyright
        = t('layouts.footer.copy_right')
        strong
          span
            | Athena
        = t('layouts.footer.reserved')
      .credits
        = t('layouts.footer.design')
    .social-links.text-center.text-md-right.pt-3.pt-md-0
      a.twitter[href="#"]
        i.fab.fa-twitter
      a.facebook[href="#"]
        i.fab.fa-facebook
      a.instagram[href="#"]
        i.fab.fa-instagram
      a.linkedin[href="#"]
        i.fab.fa-linkedin

app/views/shared/_footer_root.html.erb
<!-- Site footer -->
<footer class="site-footer">
  <div class="container">

    <div class="row">

      <div class="col-md-3 col-sm-12 col-xs-12 link-footer">
        <h6><%= t('layouts.footer.about') %></h6>
        <p class="text-justify">
          <%= t('layouts.footer.vision') %>
        </p>
      </div>

      <div class="col-md-3 col-sm-4 col-xs-4">
        <div class="link-footer">
          <h6><%= t('layouts.footer.contact') %></h6>
          <div>
            <i class="fas fa-phone"></i>
            <span> <%= t('layouts.footer.phone') %> <%= link_to "(+84) 123 456 789", "tel:0123456789" %></span>
          </div>
          <div>
            <i class="fas fa-envelope"></i>
            <span> Email: <%= link_to "jobup@gmail.com", "mailto:jobup@gmail.com", target: '_blank'  %></span>
          </div>
          <div>
            <i class="fas fa-map-marker-alt"></i>
            <span> <%= t('layouts.footer.location') %></span>
          </div>
        </div>
      </div>

      <div class="col-md-3 col-sm-4 col-xs-4 ">
        <div class="link-footer">
          <h6><%= t('layouts.footer.jobs_by_type') %></h6>
          <div class="footer-links" id="link-job-type">
            <div>Full time</div>
            <div>Part time</div>
            <div>Freelance</div>
            <div>Contract</div>
          </div>
        </div>
      </div>

      <div class="col-md-3 col-sm-4 col-xs-4">
        <div class="link-footer">
          <h6><%= t('layouts.footer.jobs_by_city') %></h6>
          <div class="footer-links" id="link-job-location">
            <div><%= t('layouts.footer.ha_noi') %></div>
            <div><%= t('layouts.footer.da_nang') %></div>
            <div><%= t('layouts.footer.ho_chi_minh') %></div>
            <div><%= t('layouts.footer.others') %></div>
          </div>
        </div>
      </div>

    </div>

    <hr>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-6 col-xs-12">
        <p class="copyright-text"> 
          <%= t('layouts.footer.copyright') %> <span> &copy; </span>
          <%= link_to 'JobUp', root_path %>
        </p>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="social-icons">
          <li><%= link_to '', 'https://www.facebook.com/sun.awesome.academy/', target: '_blank', class: "facebook fab fa-facebook" %></li>
          <li><%= link_to '', 'https://github.com/awesome-academy', target: '_blank', class: "github fab fa-github" %></li>
          <li><%= link_to '', 'https://www.instagram.com/awesomeacademyhn', target: '_blank', class: "instagram fab fa-instagram" %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.slim
header#header.fixed-top
  .container
    nav.navbar.navbar-expand-xl
      = link_to  "Athena", root_path, class: "navbar-brand logo"
      .col-sm-5.search-course
        .cover
          = form_tag "/search", method: "get", class: "forms-group" do
            = text_field_tag :query, params[:query], class: "input-search-course", placeholder: t("course.search_placeholder")
            = button_tag class: "btn-search-course" do
              i.fa.fa-search
      button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContentXL" aria-controls="navbarSupportedContentXL" aria-expanded="false" aria-label="Toggle navigation"]
        span.navbar-toggler-icon
      #navbarSupportedContentXL.collapse.navbar-collapse
        ul.navbar-nav.ml-auto
          li.nav-item
            = link_to t('layouts.header.home'), root_path, class: "nav-link"
          li.nav-item
            = link_to t('layouts.header.about'), about_path, class: "nav-link"
          li.nav-item
            = link_to t('layouts.header.course'), courses_path, class: "nav-link"
          li.flag
            = link_to image_tag('en.png'), locale:"en" if I18n.locale == :vi
          li.flag
            = link_to image_tag('vi.png'), locale:"vi" if I18n.locale == :en
        - unless signed_in?
          li.nav-item.get-login-btn
            = link_to t('layouts.header.log_in') , new_user_session_path
        - else
          li.nav-item.nav-link.dropdown
            a#navbarDropdownXL.nav-link.dropdown-toggle[href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
              = current_user.full_name.capitalize
            .dropdown-menu[aria-labelledby="navbarDropdownXL"]
              = link_to t("layouts.header.profile"), current_user, class: "dropdown-item"
              = link_to "Admin", admin_path, class: "dropdown-item" if is_admin?
              = link_to t("layouts.header.password_reset"), edit_user_registration_path, class: "dropdown-item" unless current_user.provider
              = link_to t("layouts.header.log_out"), destroy_user_session_path, method: :delete, class: "dropdown-item"

app/views/shared/_header2.html.erb
<!-- start home -->
<section id="home">
  <nav class="navbar navbar-default navbar-expand-md navbar-fixed-top templatemo-nav">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>                        
        </button>
        <%= link_to 'JobUp', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Blog', blog_path %></li>
          <li><%= link_to t('employer.employers'), employers_path %></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <p> Hello
                  <%= current_user.first_name %><span class="caret"></span>
                </p>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to t('layouts.header.account_setting'), edit_user_registration_path %></li>
                <% if current_user.user_type == 'candidate' %>
                  <li><%= link_to t('layouts.header.profile'), candidate_path(current_user.candidate) %></li>
                <% elsif current_user.user_type == 'employer' %>
                  <li><%= link_to t('layouts.header.profile'), employer_path(current_user.employer) %></li>
                <% end %>
                  <li><%= link_to t('layouts.header.log_out'), destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to t('layouts.header.log_in'), new_user_session_path %>
            </li>
            <li>
              <%= link_to t('layouts.header.sign_up'), new_user_registration_path %>
            </li>
          <% end %>
          <li><%= link_to image_tag('en.png'), locale:"en" if I18n.locale == :vi %>  </li>
          <li><%= link_to image_tag('vi.png'), locale:"vi" if I18n.locale == :en %>  </li>
        </ul>
      </div>
    </div>
  </nav>
</section>
<!-- end home -->

app/views/shared/_header_root.html.erb
<!-- start home -->
<section id="home">
  <nav class="navbar navbar-default navbar-expand-md navbar-fixed-top templatemo-nav">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'JobUp', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t('employer.employers'), employers_path %></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <p> <%= t('common.hello')%>
                  <%= current_user.first_name %><span class="caret"></span>
                </p>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to t('layouts.header.account_setting'), edit_user_registration_path %></li>
                <% if current_user.user_type == 'candidate' %>
                  <li><%= link_to t('layouts.header.profile'), candidate_path(current_user.candidate) %></li>
                <% elsif current_user.user_type == 'employer' %>
                  <li><%= link_to t('layouts.header.profile'), employer_path(current_user.employer) %></li>
                <% elsif current_user.admin? %>
                  <li><%= link_to t('layouts.header.admin'), rails_admin_path %></li>
                <% end %>
                  <li><%= link_to t('layouts.header.log_out'), destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to t('layouts.header.log_in'), new_user_session_path %>
            </li>
            <li>
              <%= link_to t('layouts.header.sign_up'), new_user_registration_path %>
            </li>
          <% end %>
          <li><%= link_to image_tag('en.png'), locale:"en" if I18n.locale == :vi %>  </li>
          <li><%= link_to image_tag('vi.png'), locale:"vi" if I18n.locale == :en %>  </li>
        </ul>
      </div>
    </div>
  </nav>
</section>
<!-- end home -->
<button class="btn btn-primary btn-lg back-to-top" data-toggle="tooltip" data-placement="left">
  <span class="glyphicon glyphicon-chevron-up"></span>
</button>