config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|vi/ do
    root 'home#index'

    get "/about", to: "home#about"
    get "/search", to: "courses#search"
    resources :courses
    resources :review_courses, except: [:new, :show]
    devise_for :users, skip: :omniauth_callbacks, controllers: { sessions: "sessions" }
    resources :users, except: [:new, :create]
    resources :lessons, only: :show
    resources :registers, only: [:edit, :update]
    resources :quiz_results, only: :create
    get "course/like/:course_id", to: "likes#save_like", as: :like_course
    resources :registers, only: :create

    namespace :admin do
      get "/", to: "base#index"
      get "/range", to: "base#range"
      resources :courses
      resources :users
      devise_scope :user do
        get "/login", to: "sessions#new"
        post "/login", to: "sessions#create"
        delete "/logout", to: "sessions#destroy"
      end
      namespace :charts do
        get "all_users_provider"
        get "users_registered_by"
        get "users_registered_course"
        get "users_registered_course_type"
      end
    end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "omniauth_callbacks" }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :comment_lessons, dependent: :destroy
  has_many :quiz_questions, dependent: :destroy

  validates :lesson_type, :lesson_sequence, :lesson_name, presence: true
  validates :lesson_name, length: { maximum: Settings.length.lesson_name.maximum }
  validates :min_point, numericality: { only_integer: true, greater_than_or_equal_to: Settings.mark.min },
                        presence: true, if: Proc.new { |lesson| lesson.quiz? }
  validates :video_url, presence: true, if: Proc.new { |lesson| lesson.video? }
  enum lesson_type: Settings.lesson_type.to_h
  accepts_nested_attributes_for :quiz_questions,
                                reject_if: proc { |attribute| attribute["quiz_question"].blank? }, allow_destroy: true
  validate :max_point

  def max_point
    if min_point && min_point > quiz_questions.length
      errors.add(:min_point, "can't greater than number of questions")
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = Lesson.find params[:id]
    @lessons = @lesson.course.lessons
    @register = Register.find_by(course_id: @lesson.course_id, user_id: current_user.id)
    @result = QuizResult.find_by(user_id: current_user.id, lesson_id: @lesson.id)
    @quizzes = @lesson.quiz_questions
    @max_point = @quizzes.length
    respond_to do |format|
      format.js { @current_test = @lesson }
    end
  end
end

app/views/lessons/_lesson.html.slim
.card.card-lesson-show.lesson-locked
  .card-body
    .lesson-name-show.row
      = link_to lesson.lesson_name, lesson, remote: true, class: "btn btn-link lesson-item"
      .lesson-lock.fa.fa-lock.col-sm-1

app/views/lessons/_lesson_unlock.html.slim
- @lessons_unlock.each do |lesson|
  .card.card-lesson-show.lesson-unlock
    .card-body
      .lesson-name-show.row
        = link_to lesson.lesson_name, lesson, remote: true, class: "btn btn-link lesson-item"

app/views/lessons/_quiz.html.slim
- if @result || current_user.is_admin?
  = render "quiz_results/result"
- else
  = render "lessons/quiz_form"

app/views/lessons/_quiz_form.html.slim
.card.card-quiz
  .card-header.header-quiz-result
    strong.quiz-title
      = @lesson.lesson_name
  .card-body
    = form_tag quiz_results_path, remote: true do
      = hidden_field_tag :lesson_id, @lesson.id
      - @quizzes.each_with_index do |quiz, i|
        .question
          = i + 1
          |.
          = quiz.quiz_question
          - quiz.quiz_choice.each_with_index do |answer, idx|
            .answer.row
              .user-answer
                = check_box_tag "user_answer[#{quiz.id}][]", answer.last["label"]
              .label-answer
                = answer.last["label"]
                |.
              .tex-answer
                = answer.last["text"]
      = submit_tag t("lesson.submit"), class: "btn btn-success"
#fail-result

app/views/lessons/_show_lesson.html.slim
.card.card-lesson-show.lesson-unlock
  .card-body
    .lesson-name-show.row
      = link_to @lesson.lesson_name, @lesson, remote: true, class: "btn btn-link lesson-item"

app/views/lessons/_video.html.erb
<h5 class="lesson-name"> <%= @lesson.lesson_name %></h5>
<div id="iframe-lesson">
  <iframe class="lesson-video" src="<%= @lesson.video_url %>" width="720" height="480" frameborder="0" allowfullscreen allow="encrypted-media"></iframe>
</div>
<script type="text/javascript">
  <% if @register %>
    var step = <%= @register.lesson_step %>;
  <% end %>
  $("#iframe-lesson iframe").on("load", function () {
    var iframe = $('#iframe-lesson iframe');
    var player = new Vimeo.Player(iframe);

    player.on('ended', function() {
      var next_element = $(".lessons-list .card-lesson-show").get(<%= @lesson.lesson_sequence %>);
      <% if @register && @lesson.video? && (@register.lesson_step == @lesson.lesson_sequence) %>
        if (next_element != undefined ) {
          $.ajax({
            method: "PATCH",
            url: "/registers/" + <%= @register.id %>,
            data: { register: { lesson_step: step + 1 } }
          });
        }
      <% end %>
      <% if ((@register && @register.lesson_step > @lesson.lesson_sequence) || current_user.is_admin?) %>
        $.ajax({
          method: "GET",
          url: $(next_element).find("a").attr("href"),
          success: function () {
            $(".lessons-list").find(".card-body").removeClass("active");
            $(next_element).find(".card-body").addClass("active");
          }
        });
      <% end %>
    });
  })
</script>

app/views/lessons/show.js.erb
lesson = $(".lessons-list .card-lesson-show").get(<%= @lesson.lesson_sequence %> - 1);
$(".lessons-list").find(".card-body").removeClass("active");
$(lesson).find(".card-body").addClass("active");
<% if @lesson.video? %>
  $(".lesson-content").html("<%= j render 'lessons/video'%>");
<% elsif @lesson.quiz? %>
  $(".lesson-content").html("<%= j render 'lessons/quiz'%>");
<% end %>